# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
      build: ../../../
      #restart: always
      ports:
        - 3000:3000
      depends_on:
        - db  # Attendendre que la base de données PostgreSQL soit ok avant de démarrer l'application

volumes:
      postgres-data: